### PR TITLE
I created a category item list page.

### PR DESCRIPTION
**Pull request by KIN181**
I created a category item list page.
Creating css files.
I am creating a controller and route to display viw.
Please check the comments in the file for details.

### CODE REVIEW

**Comment by Ditzler01** [comment]
Please resolve conflicts.

**Comment by KIN181** [comment]
As for how to resolve the conflict, is it okay to simply delete the route?
When I checked, the other Route was probably written on the same line, so should I write it somewhere other than that line? Is the Route description below itself the cause of the conflict?

Route::get('/categoryitem/categoryitemlist',[CategoryItemListController::class,'index'])->name('categoryitem.categoryitemlist');

**Comment by KIN181** [comment]
Due to a Route conflict, the description line has been moved to the bottom. Please confirm.

**Comment by keanbillyfernandez** [comment]
@KIN181 , For fixing the conflict files, You must pull first and then push the updates in your current branch

**Comment by Ditzler01** [comment]
Please resolve the conflicts.

**Comment by KIN181** [comment]
please check out it

**Pull request merged**
