### PR TITLE
UI/transaction

### PR DESCRIPTION
**Pull request by hikaritanaka1695**
I can't solve the problem with the JavaScript part. Please confirm.

### CODE REVIEW

**Comment by hikaritanaka1695** [comment]
Added a mechanism to add items with Ditzler
Mix is ​​conflicting because I personally tried to solve the problem using a JavaScript framework. I tried removing the framework, but it didn't work. I would like to know how to resolve the conflict.

**Comment by hikaritanaka1695** [comment]
Edited the User database. We have also created a new database related to Cart.

**Comment by Ditzler01** [comment]
Please fix the conflicts.
Thank you.

**Comment by hikaritanaka1695** [comment]
The conflict has been fixed
Cart somehow
I created a relationship between table editing and cart_item.
It seems that the Item has been added, but it is not displayed properly in the Order list. Please check tomorrow. I will push it to Girhub

**Pull request merged**
